build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
labels:
  org.opencontainers.image.title: "URnetwork Provider"
  org.opencontainers.image.description: "URnetwork community provider add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/harry2690/urnetwork-homeassistant-addon"
  org.opencontainers.image.licenses: "MIT"
