build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:15.0.7"
  amd64: "ghcr.io/hassio-addons/base/amd64:15.0.7"
  armhf: "ghcr.io/hassio-addons/base/armhf:15.0.7"
  armv7: "ghcr.io/hassio-addons/base/armv7:15.0.7"
labels:
  org.opencontainers.image.title: "URnetwork Provider"
  org.opencontainers.image.description: "URnetwork community provider add-on for Home Assistant"
  org.opencontainers.image.source: "https://github.com/harry2690/urnetwork-homeassistant-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
