name: URnetwork Provider
version: "1.0.25"
slug: urnetwork-addon
description: "URnetwork community provider add-on for Home Assistant"
url: "https://github.com/harry2690/urnetwork-homeassistant-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
map:
  - addon_config:rw
  - /var/run/docker.sock:/var/run/docker.sock
options:
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  web_port: 8099
  log_level: info
schema:
  ssl: bool
  certfile: str
  keyfile: str
  web_port: port
  log_level: list(trace|debug|info|notice|warning|error|fatal)
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "URnetwork Web UI"
host_network: false
privileged:
  - SYS_ADMIN
docker_api: true
hassio_api: true
hassio_role: default
homeassistant_api: false
auth_api: false
webui: "http://[HOST]:[PORT:8099]/"
