name: Build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  information:
    name: Gather add-on information
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.information.outputs.architectures }}
      build: ${{ steps.information.outputs.build }}
      description: ${{ steps.information.outputs.description }}
      name: ${{ steps.information.outputs.name }}
      slug: ${{ steps.information.outputs.slug }}
      target: ${{ steps.information.outputs.target }}
      version: ${{ steps.information.outputs.version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get information
        id: information
        uses: home-assistant/actions/helpers/info@master

  build:
    name: Build ${{ matrix.arch }} add-on
    needs: information
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ${{ fromJson(needs.information.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get information
        id: information
        uses: home-assistant/actions/helpers/info@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.arch }} add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --addon

  publish:
    name: Publish add-on
    if: github.event_name == 'release'
    needs: [information, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target /data \
            --docker-hub ghcr.io/${{ github.repository_owner }} \
            --addon \
            --push
