name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Add-on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Add-on
        uses: frenck/action-addon-linter@v2
        with:
          path: "."
        continue-on-error: true

  build:
    name: Test build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test configuration
        run: |
          echo "Testing basic Add-on configuration..."
          if [ -f "config.yaml" ]; then
            echo "✓ config.yaml exists"
            echo "Add-on name: $(grep '^name:' config.yaml | cut -d' ' -f2-)"
            echo "Version: $(grep '^version:' config.yaml | cut -d' ' -f2-)"
          else
            echo "✗ config.yaml not found"
            exit 1
          fi

          if [ -f "Dockerfile" ]; then
            echo "✓ Dockerfile exists"
          else
            echo "✗ Dockerfile not found"
            exit 1
          fi

          echo "Basic configuration test passed!"