name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Add-on
        uses: frenck/action-addon-linter@v2
        with:
          path: "."

      - name: Build Add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 \
            --target .